/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : XLS II
 #	author : miyako
 #	12/06/13
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONMAC
#include <iconv.h>
#if PA_SMALLENDIAN
#define UTF32NATIVE "UTF-32LE"
#else
#define UTF32NATIVE "UTF-32BE"
#endif
#endif

#include "ExcelFormat.h"

using namespace ExcelFormat;
using namespace std;

BasicExcel *_workbookCreate(unsigned int *index);
void _workbookDelete(unsigned int i);
BasicExcel *_workbookGet(unsigned int i);

#if VERSIONMAC
void _copyPath(C_TEXT *t, std::string *s);
#else
void _copyPath(C_TEXT *t, std::wstring *s);
#endif

void _copyString(std::wstring *w, C_TEXT *t);
void _copyString(C_TEXT *t, std::wstring *w);

// --- File
void XLS_Create(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Load(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Save_as(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CLOSE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Workbook
void XLS_Get_total_sheets(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Add_sheet(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_sheet_name(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_sheet_name(sLONG_PTR *pResult, PackagePtr pParams);

// --- Worksheet
void XLS_Get_total_rows(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_total_columns(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_column_width(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_column_width(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Merge_cells(sLONG_PTR *pResult, PackagePtr pParams);

// --- Cell
void XLS_Clear_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_text_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_real_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_long_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_long_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_real_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_text_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_value_type(sLONG_PTR *pResult, PackagePtr pParams);

// --- Font
void XLS_SET_FONT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_GET_FONT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);

// --- Format
void XLS_SET_FORMAT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_GET_FORMAT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_format_string(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_format_string(sLONG_PTR *pResult, PackagePtr pParams);

// --- Format (2)
void XLS_Get_wrapping(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_SET_WRAPPING(sLONG_PTR *pResult, PackagePtr pParams);
