/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-XLS-II.h
 #	source generated by 4D Plugin Wizard
 #	Project : XLS II
 #	author : miyako
 #	2019/12/20
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_XLS_II_H
#define PLUGIN_XLS_II_H

#include "4DPluginAPI.h"
#include "iconv.h"
#include "BasicExcel/ExcelFormat.h"

#include "C_LONGINT.h"
#include "C_TEXT.h"
#include "C_REAL.h"

#include <mutex>

using namespace ExcelFormat;
using namespace std;

BasicExcel *_workbookCreate(unsigned int *index);
void _workbookDelete(unsigned int i);
BasicExcel *_workbookGet(unsigned int i);

void _setString(C_TEXT &t, wstring &p);
void _getString(wstring &p, C_TEXT &t);

#if VERSIONMAC
void _getPath(C_TEXT &t, string &p);
#else
void _getPath(C_TEXT &t, wstring &p);
#endif

void _setANSIString(C_TEXT &t, string &p, C_TEXT &encoding);
void _getANSIString(string &p, C_TEXT &t, C_TEXT &encoding);

#pragma mark -

void XLS_Create(PA_PluginParameters params);
void XLS_Load(PA_PluginParameters params);
void XLS_Save_as(PA_PluginParameters params);
void XLS_CLOSE(PA_PluginParameters params);
void XLS_Get_total_sheets(PA_PluginParameters params);
void XLS_Add_sheet(PA_PluginParameters params);
void XLS_Get_sheet_name(PA_PluginParameters params);
void XLS_Set_sheet_name(PA_PluginParameters params);
void XLS_Get_total_rows(PA_PluginParameters params);
void XLS_Get_total_columns(PA_PluginParameters params);
void XLS_Set_column_width(PA_PluginParameters params);
void XLS_Get_column_width(PA_PluginParameters params);
void XLS_Merge_cells(PA_PluginParameters params);
void XLS_Clear_value(PA_PluginParameters params);
void XLS_Get_text_value(PA_PluginParameters params);
void XLS_Get_real_value(PA_PluginParameters params);
void XLS_Get_long_value(PA_PluginParameters params);
void XLS_Set_long_value(PA_PluginParameters params);
void XLS_Set_real_value(PA_PluginParameters params);
void XLS_Set_text_value(PA_PluginParameters params);
void XLS_Get_value_type(PA_PluginParameters params);
void XLS_SET_FONT_PROPERTY(PA_PluginParameters params);
void XLS_GET_FONT_PROPERTY(PA_PluginParameters params);
void XLS_SET_FORMAT_PROPERTY(PA_PluginParameters params);
void XLS_GET_FORMAT_PROPERTY(PA_PluginParameters params);
void XLS_Get_format_string(PA_PluginParameters params);
void XLS_Set_format_string(PA_PluginParameters params);
void XLS_Get_wrapping(PA_PluginParameters params);
void XLS_SET_WRAPPING(PA_PluginParameters params);

#endif /* PLUGIN_XLS_II_H */
