/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : XLS II
 #	author : miyako
 #	2013/12/09
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#include "BasicExcel/ExcelFormat.h"
#include "iconv/iconv.h"

using namespace ExcelFormat;
using namespace std;

BasicExcel *_workbookCreate(unsigned int *index);
void _workbookDelete(unsigned int i);
BasicExcel *_workbookGet(unsigned int i);

void _setString(C_TEXT &t, wstring &p);
void _getString(wstring &p, C_TEXT &t);

#if VERSIONMAC
void _getPath(C_TEXT &t, string &p);
#else
void _getPath(C_TEXT &t, wstring &p);
#endif

void _setANSIString(C_TEXT &t, string &p, C_TEXT &encoding);
void _getANSIString(string &p, C_TEXT &t, C_TEXT &encoding);

// --- File
void XLS_Create(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Load(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Save_as(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CLOSE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Workbook
void XLS_Get_total_sheets(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Add_sheet(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_sheet_name(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_sheet_name(sLONG_PTR *pResult, PackagePtr pParams);

// --- Worksheet
void XLS_Get_total_rows(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_total_columns(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_column_width(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_column_width(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Merge_cells(sLONG_PTR *pResult, PackagePtr pParams);

// --- Cell
void XLS_Clear_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_text_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_real_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_long_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_long_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_real_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_text_value(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_value_type(sLONG_PTR *pResult, PackagePtr pParams);

// --- Font
void XLS_SET_FONT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_GET_FONT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);

// --- Format
void XLS_SET_FORMAT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_GET_FORMAT_PROPERTY(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_format_string(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Set_format_string(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_Get_wrapping(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_SET_WRAPPING(sLONG_PTR *pResult, PackagePtr pParams);
